# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: githubPEM
  displayName: 'Download Github PEM'
  inputs:
    secureFile: 'github.pem'
- bash: |   
   eval $(ruby -e "require 'openssl'; require 'jwt'; private_pem = File.read(ENV['GITHUB_PEM_PATH']); private_key = OpenSSL::PKey::RSA.new(private_pem); payload = { iat: Time.now.to_i - 60, exp: Time.now.to_i + (10 * 60), iss: ENV['GITHUB_APP_ID'] }; jwt = JWT.encode(payload, private_key, 'RS256'); puts 'PUSH_JWT='+jwt;")
   echo $PUSH_JWT
   curl -i -X POST \
     -H "Authorization: Bearer $PUSH_JWT" \
     -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/app/installations/$GITHUB_APP_INSTALLATION_ID/access_tokens 2>/dev/null | jq -r '.token'
  displayName: 'Push to Github'
  env:
    GITHUB_PEM_PATH: $(githubPEM.secureFilePath)
    GITHUB_APP_ID: $(GITHUB_APP_ID)
    GITHUB_APP_INSTALLATION_ID: 16830466
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
